### ISSUE TITLE
Feature: hidden inbox

### ISSUE THREAD

**Issue by FlorentCoppint** [SMSSecure/SMSSecure#103]
Hi everyone,

I'm an happy user of SMSSecure.

I would like to suggest a feature : a secondary hidden inbox, for some contacts.

We could access to this hidden inbox via a menu, or via a special phone number, and could be protected with a (small) PIN.
The goal is to hide messages of previously selected contacts from main Inbox of SMSSecure, and to have it in a hidden one.

This feature exists in Handcent SMS ("Private box") and is very useful.

Before I upgrade to Kitkat, I was using Handcent+SMSSecure, but it seems that with Kitkat we can no more use 2 SMS apps :(

Do you think this feature is easy to implement in SMSSecure ?

I work in IT (more systems&networks), I know how to develop, but I don't have any knowledge in Android dev :( I set-up SMSSecure dev environment, but I'm lost, I don't know where to start...

Please tell me what you think of a such feature :)

Thank you.
Flo

**Comment by pR0Ps** [comment]
We already provide the ability to protect your messages from being viewed by using a passphrase (Settings -> App protection -> Enable passphrase). This actually encrypts the messages on disk (something which the "privacy box" feature is [lacking](http://www.droidforums.net/threads/handcent-privacy-box-password-reset.210372/#post-2273256)).

Since you can already encrypt your messages (and set a timeout for auto-locking), I'm not sure having a secondary "extra private" inbox would provide any extra privacy, just increase the complexity of the app and the UI.

That being said, we follow TextSecure in features and functionality pretty closely. If they add it (you can ask), we'll pull it in.

**Comment by FlorentCoppint** [comment]
Hi,
I know about passphrase of course :+1: 
The goal is to hide some conversations even if you are "forced" to open your inbox.
Or just to prevent people seeing some conversation when they can see your inbox.
