### ISSUE TITLE
Add autodestruction secret password function

### ISSUE THREAD

**Issue by Amadren** [SMSSecure/SMSSecure#114]
I think it would be great to add a secret password that when entered in the "decrypt your data" form would remove all messages.

**Comment by johanw666** [comment]
Because? This kind of question comes up in every project that deals with encryption. The problem with it is that any serious investigator will investigate your device only after a backup has been made so this would solve nothing. First law of forensic data analysis: backup!

A password that shows no data might be handy against a suspicious girl/boyfriend, but for that see the replies in a similar feature request #103.

**Comment by Amadren** [comment]
Nope. It would be a secondary password that would remove every messages. So imagine that for some reasons someone comes in your house and want to see your data. He will come and open your phone. You just have to type this password and every messages would be erased.

**Comment by BastienLQ** [comment]
This feature would add more complexity to the code while not adding more security. If someone wants to read your messages, he just needs to backup `/data`: whatever the password you gave, the attacker have a copy of the DB.
