### ISSUE TITLE
Show send time instead of receive time

### ISSUE THREAD

**Issue by der-stefan** [SMSSecure/SMSSecure#116]
Currently, SMSSecure only shows the time, a SMS was received. If you switch on your phone after a longer time and receive SMS your provider stored for you, it is not possible to see the time when your contact had sent it.
The normal SMS app (at least in Cyanogenmod) has an option in the settings, if you want to see the send or receive time of a message.
This feature would be nice in SMSSecure, too.

**Comment by BastienLQ** [comment]
I can see both Sent and Received dates:
![screenshot_2015-04-30-01-04-55](https://cloud.githubusercontent.com/assets/7220484/7403368/4b952702-eed5-11e4-85a3-899076fd439a.png)

**Comment by justbittin** [comment]
He is talking about in message view, not information/detail view.

Regular SMS apps tell you when it was sent, not recieved.  If the phone was off and i get 5 messages, they all say 'now' instead of time sent.  That is the important time, not the recieved.

**Comment by BastienLQ** [comment]
OK, I misread... We could add an option to display the sent date instead of received date, like in the AOSP message app.

**Comment by pR0Ps** [comment]
More information: http://forum.xda-developers.com/showpost.php?p=51414758&postcount=2

**Comment by justbittin** [comment]
Would be a great enhancement.

**Comment by der-stefan** [comment]
At least an option would be great in the settings: "Show send time"

**Comment by breversa** [comment]
Agreed with @justbittin and @der-stefan  : displaying the sent time is sounder than the received time, and should (at least IMO) be the default setting, with an option to show received time instead.

However, even the CyanogenMod SMS app, messages are still displayed in the order they are received, even is "show sent time" is on.

Why not offer an option to display the messages in the sent time order ? I would be really helpful in the situations where either your (or the person you're communicating with, or both) phone is unable to receive text messages for an extended period of time (either because of servicing, prolonged stay in no-service area, etc.), then comes back on and start receiving the tens/hundreds of messages sent to you during that time : many of them would probably be "out of order".
