### ISSUE TITLE
The cursor has disappeared

### ISSUE THREAD

**Issue by Ezelty** [SMSSecure/SMSSecure#125]
Hi,
with the 0.7.0 version, the cursor has disappeared. In the older versions, there was a cursor just after the letter you were typing. In the other applications I use in which I can type text, I don't have any problem.
I use SMSSecure v0.7.0 and Android 4.4.4. 

![no cursor](https://cloud.githubusercontent.com/assets/12199874/7536715/71c002da-f592-11e4-8be7-6a68900a0e3e.png)
![no cursor even with the blue arrow](https://cloud.githubusercontent.com/assets/12199874/7536716/7284cd72-f592-11e4-8d4d-50eb993dac9a.png)

**Comment by johanw666** [comment]
This also happened in the parent project: https://github.com/WhisperSystems/TextSecure/issues/3134

**Comment by johanw666** [comment]
I'm not very familiar with Android development, but searching for "text cursor color" I find this: http://stackoverflow.com/questions/7238450/set-edittext-cursor-color, where is pointed to the variable android:textCursorDrawable. Searching for this I find this referenced in only one place in the source, in the build tools in \build\intermediates\exploded-aar\com.android.support\appcompat-v7\22.1.1\res\values-v12\values.xml. The build tools have recently been upgraded from 21.0.3 to 22.1.1; in 21.0.3 there are no references to android:textCursorDrawable. Maybe the bug is related to this upgrade?

**Comment by johanw666** [comment]
Problem solved, following a hint from @mcginty I made some changes in  /src/org/smssecure/smssecure/components/ComposeText.java
```java
import android.support.v7.widget.AppCompatEditText;
...
public class ComposeText extends AppCompatEditText {
```
I commented out the constructor with 4 arguments since AppCompatEditText does not have such a constructor. And the cursor is blinking again.
