### ISSUE TITLE
Ubuntu Touch port [feature request]

### ISSUE THREAD

**Issue by HLFH** [SMSSecure/SMSSecure#138]
Hi,

A lot of Ubuntu users would love a port of SMSSecure on Ubuntu Touch.
Will that happen a day?

Thanks in advance,

**Comment by pR0Ps** [comment]
This specific project won't support it (we have our hands full with Android), but if you know people who are more familiar with development for the Ubuntu phone ecosystem, ask if they would consider developing a compatible client. The more platforms the better.

However, with that being said, the Ubuntu APIs that SMSSecure needs are marked as being reserved for Ubuntu-provided apps (as far as I understand it). This is a pretty big barrier for non-developers since it will never be as easy as just installing an app (Unless the APIs change).
