### ISSUE TITLE
How different is SMSSecure from TextSecure?

### ISSUE THREAD

**Issue by jwalantsoneji** [SMSSecure/SMSSecure#164]
Hello,
Read in the SMSSecure description in f-droid that it's using TextSecure in it.
Would like to know how different are these two apps.
Regards,
Jwalant

**Comment by johanw666** [comment]
SMSsecure sends plaintext SMS/MMS and encrypted SMS/MMS.

TextSecure (since version 2.7) can send plaintext SMS/MMS and encrypted push messages via the data channel. both:

TextSecure 2.6.4 used to be a combination of both: it could send plaintext SMS/MMS, encrypted SMS/MMS and encrypted push messages. Unfortunately TextSecure decided to remove the encrypted SMS/MMS functionality and this triggered SMSSecure as a a fork that removed push messaging and kept the encrypted SMS/MMS.
