### ISSUE TITLE
Add option: Auto-retrieve MMS

### ISSUE THREAD

**Issue by SlavikCA** [SMSSecure/SMSSecure#211]
Currently, MMS are always auto-retrieved.

However, in light of "Stagefright" vulnerability:
https://nakedsecurity.sophos.com/2015/07/28/the-stagefright-hole-in-android-what-you-need-to-know/

Need to have option to turn off Auto-retrieval of MMS.

Related to this upstream issue:
https://github.com/WhisperSystems/TextSecure/issues/3817
However, @moxie0 comment seems to be not correct: as per vulnerability, it doesn't require user to click / open anything...

**Comment by johanw666** [comment]
This does not help protecting against Stagefright becauae video is not auto-played. See also https://github.com/WhisperSystems/TextSecure/issues/3817#issuecomment-125300940

**Comment by SlavikCA** [comment]
So, does that mean, that if I, as the user, will not open (play) MMS with malicious content, then I'm safe from the "Stagefright" vulnerability?

**Comment by SlavikCA** [comment]
As I'm looking at technical details here:
http://fortune.com/2015/07/28/stagefright-google-android-security/
it seems, that bug reproduce is not while media is PLAYED, but while message DOWNLOADED:

>Stagefright (the library, not the bug) helps phones unpack multimedia messages. It enables Android phones to interpret MMS content (multimedia message service content), which can contain videos, photos, audio, text. The bugs are in that library.
>That means an attacker can infect your device simply by sending you a malicious MMS message. In fact, a victim doesn’t even have to open a booby-trapped message for the attack to spring. Once the message received, your phone is toast.

**Comment by pR0Ps** [comment]
Nobody knows yet exactly what triggers the bug since the researchers are waiting for BlackHat/DefCon next week to release the full details.

My understanding is that the bug is triggered when the MMS is viewed. The reason everyone is reporting that it happens automatically when the message is downloaded is because a lot of clients automatically download the MMS, process it (triggering the bug), and show a preview in the notification.

We don't do any processing until the user manually taps a message and confirms a warning dialog (as mentioned by @moxie0 in the upstream issue).

**Comment by ToNIX-** [comment]
Bumping this functionality for a simple reason. If auto retrieve is turned off (like in Messenger) and the data is off, you get a notification of an incoming MMS. You can then turn data on and press the notification to download the MMS.

Would this be something possible with Signal?
