### ISSUE TITLE
extend block function to "spam" function

### ISSUE THREAD

**Issue by zoff99** [SMSSecure/SMSSecure#249]
now you can block a contact, but then you will not recevie any messages from that contact.

please extend this function to a spam function (see samsung stock sms app)

spam function:

1. in settings add a feature to add "words" to a spam-word-list
2. in settings add a feature to add "phone numbers" to a spam-phone-number-list

when a new sms/mss is received:
- check if it's coming from a number on the spam-phone-number-list, if yes then
  - do NOT play a sound
  - do NOT show a notification
  -  but DO receive the sms/mms and move it to a spam folder (or just mark it as spam) so that the user can still read it and delete it later

- check if it's containing any word from the spam-word-list, if yes then
  - do NOT play a sound
  - do NOT show a notification
  -  but DO receive the sms/mms and move it to a spam folder (or just mark it as spam) so that the user can still read it and delete it later

**Comment by zoff99** [comment]
for how samsung does it see:

![aa](http://1.bp.blogspot.com/-N7ZC7wjRrFw/UwO-y8QYBDI/AAAAAAAAA88/vMW5PgFf95E/s1600/view+spam+messages+in+Galaxy+S4.png)

![bb](http://3.bp.blogspot.com/-IhkwEmag5N0/UwO-zAIe_6I/AAAAAAAAA9E/n1TTkH76s18/s1600/register+phrases+as+spam+in+Galaxy+S4.png)

**Comment by johanw666** [comment]
Is spam via SMS still an issue in some countries? I have never had any spam via SMS (only once a message for the previous owner of a number). Although on Viber it has been quite an annoyance recently.

However, I doubt the issue is large anough to spend a huge development effort into this, and specialised external programs who handle this exist. I doubt very much anyone will send encrypted spam sms messages that can't be read by those external tools (they would have to start with key exchange anyway).Further, the effort involved will be HUGE - blocking works different on different Android versions or even among different vendors. Even specialised call and sms blockers will usually work only on a subset of all devices (yes, I tried).

**Comment by zoff99** [comment]
i don't see the huge work? the block function is alread there.
please at least DO NOT delete messages from blocked contacts.
this should not be much work to do.

there are lots of SPAM sms here from phone comanpies.
also you sometimes get acknowledge sms from some services for which u don't what to have a sound/notification/LED. but you need to read those later for confirmation.

**Comment by pR0Ps** [comment]
Instead of blocking the contacts, you could just mute them. Then you wouldn't receive notifications for them but messages sent from would still come through and wouldn't be deleted.

**Comment by zoff99** [comment]
mute for unlimited time is NOT implemented!
1 year is the maximum now.

then please implement mute -> permanent

**Comment by pR0Ps** [comment]
@zoff99: Tell you what - set those contacts to muted for a year now and sometime within the next year I'll implement a permanent option.

**Comment by zoff99** [comment]
@pR0Ps  ```... within the next year I'll implement a permanent option```
:-(
