### ISSUE TITLE
MMS download texts are capped ambiguous

### ISSUE THREAD

**Issue by johanw666** [SMSSecure/SMSSecure#258]
This is what I see on my Samsung Galaxy S4 mini: the parts that are shown are the same.
SMSSecure 0.12. Perhaps 2 lines would be clearer?

![smssecure_mms](https://cloud.githubusercontent.com/assets/8427572/10305371/272c63e4-6c20-11e5-9f06-6a632253d147.png)

**Comment by pR0Ps** [comment]
I don't think this can be fixed by just shortening the strings. This means that people with smaller devices or running with the text size accessibility option cranked up will still see the ambiguous strings.

I would suggest having an "MMS" heading with "Auto-retrieve" and "Roaming auto-retrieve" options under it. This is what Google Messanger does and it's pretty clear.

![screenshot_2015-10-06-21-18-20](https://cloud.githubusercontent.com/assets/466941/10327116/89bc293a-6c71-11e5-80d2-a224a97e2f6a.png)
