### ISSUE TITLE
Encrypt message outside of SMSSecure

### ISSUE THREAD

**Issue by FlorentCoppint** [SMSSecure/SMSSecure#280]
Hi everyone,

I would like to know if it is possible to encrypt a message outside of the app, to send it encrypted to a SMSSecure user ?

In fact, my Mobile Service Provider gives me a HTTP API to send SMS. I can send non-encrypted (clear) SMS.

I would like to encrypt my message (in bash for exemple, or PHP, or what else) and then send encrypted message via the API.

Is it difficult to do ?

Thank you.

**Comment by pR0Ps** [comment]
It would be extremely difficult.

You could write a script that implements the [same protocol](https://github.com/WhisperSystems/Signal-Android/wiki/ProtocolV2) in another program, but since the protocol involves a ratcheting mechanism, if you send messages with another program, you'll run into issues with keeping the sessions synced up.
