### ISSUE TITLE
Include upstream changes from Signal

### ISSUE THREAD

**Issue by SecUpwN** [SMSSecure/SMSSecure#285]
Good evening developers, derived from https://github.com/JavaJens/TextSecure/issues/52#issuecomment-158616107 I would like to kindly ask you to include the upstream changes from [Signal-Android](https://github.com/WhisperSystems/Signal-Android) so that SMSSecure is also able to secure an online communication. I know you've likely thrown out any online components, but reading up on [Android: Signal ohne Google Cloud Messaging](http://www.kuketz-blog.de/android-signal-ohne-google-cloud-messaging) it made me wonder if you couldn't make `SMSSecure` become the *ultimate* encrypted messenger by also implementing the work of `LibreSignal` (fork of `Signal` without GCM)?

**Comment by BastienLQ** [comment]
- We're including upstream changes related to SMS/MMS messages (see #287);
- We won't include online chat, because (1) SMSSecure and Signal aren't incompatible (thus I suppose LibreSignal can also work on a phone where SMSSecure is installed) and (2) SMSSecure and Signal are quite different now and re-adding online chat functionalities would be a nightmare.
