### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by pR0Ps** [SMSSecure/SMSSecure#31]
The project should have a page that explains what SMSSecure is, what it isn't, where it comes from, a disclaimer saying we're not affiliated with OpenWhisperSystems or TextSecure, etc.

Something basic for when the app hits F-Droid/Play Store would go a long way.

I've made a [super basic page](http://smssecure.github.io/SMSSecure/) and tossed it on gh-pages just to get everything set up, but it definitely needs replacing.

Tasks:
- [x] Design and deploy website
- [x] Update the "invite" link in the app to the website
- [x] Update README to point to the website
- [x] Update F-Droid description to point at the website

**Comment by BastienLQ** [comment]
We should open a new project and maintain the website as an independent repository.

A one page website seems to be the best solution. We might use Bootstrap to do not waste our time. A good starting point could be [the website of Nuolezio](https://github.com/Nuolezio/homepage) (a non-profit organization in which I work): free, open-source, simple and clean.

The hosting provider can be @Nuolezio too. I don't really like gh-pages because we aren't free to do everything we would. Nuolezio provides a Heroku like hosting service and is free of charge. files.smssecure.org is already hosted by Nuolezio.

**Comment by SecUpwN** [comment]
@pR0Ps, if you guys edit the `README` properly, why not use [GitHub Pages](https://pages.github.com/)? It makes maintenance very easy since it is just anotther brnach on the same repository. Feel invited to have a look at the [page of my own projject](https://secupwn.github.io/Android-IMSI-Catcher-Detector/).

**Comment by BastienLQ** [comment]
A static website won't allow, for example, to display an RSS feed (for Git commits; yes, we could do it on a client-side, but it would exclude clients without JS support) or to catch Travis-CI builds.

**Comment by pR0Ps** [comment]
I've deleted the gh-pages branch so nobody gets confused
