### ISSUE TITLE
Selecting messages containing a phone number is difficult

### ISSUE THREAD

**Issue by johanw666** [SMSSecure/SMSSecure#35]
To select such a message, I first have to long-press it. It then selects the message and immediately deselects. After that, I can long-press the whitespace at the left and it gets selected. In TextSecure, 2.7, long-pressing the white space on the left works without long-pressing the message itself first (but long-pressing the message also fails there).

Judging from problems with TextSecure in the past with this issue, messages containing an URL have probably the same problem.

**Comment by pR0Ps** [comment]
Since this bug is also present in TextSecure and isn't specific to SMS (meaning it affects them too), please open an issue against the parent project. When it's fixed we'll pull it in.

Possibly related:
 - https://github.com/WhisperSystems/TextSecure/issues/508
 - https://github.com/WhisperSystems/TextSecure/issues/2764
