### ISSUE TITLE
Publish via multiple common distribution methods

### ISSUE THREAD

**Issue by BoBeR182** [SMSSecure/SMSSecure#4]
Publish on Google Play so semi-aware users can get updates without recompiling from source.

**Comment by BastienLQ** [comment]
SecuredText will be distributed via the Play Store, but I would prefer to use the F-Droid signed APK. F-Droid signing process is much more trustworthy than an unknown dev like me.

**Comment by BoBeR182** [comment]
I already assumed f-droid would be hosting a copy, but for non privacy awake users that I convinced to switch to textsecure in the first place, I have to now get to install a new app.

**Comment by BastienLQ** [comment]
SecuredText should be included in F-Droid during this week-end (see the MR: https://gitlab.com/fdroid/fdroiddata/merge_requests/646). For now, we cannot add SecuredText in the Play Store:
* if we put the F-Droid signed APK on the Play Store, we must wait for the MR in fdroiddata
* if we use a different key in Play Store, we must publish security policies and signing process

I prefer the first option: in both cases we will need time, and using F-Droid signed package is easier for maintainers. And in both case, installing SecuredText via the Play Store will not require F-Droid client to be installed on the device.

**Comment by BoBeR182** [comment]
Any hope of an compiled unsigned hosted APK for the time being?

**Comment by BastienLQ** [comment]
It is not possible on the Play Store, but I can compile a debug version and put it elsewhere. But pay attention: it won't be possible to upgrade SecuredText from the debug version to the signed one ; you will have to export your messages, remove SecuredText, install the signed version and then import your messages.

**Comment by BastienLQ** [comment]
Here is a debug APK: https://files.securedtext.org/org.SecuredText.SecuredText_0.3.2-debug.apk

**Comment by pR0Ps** [comment]
When this is published, make sure that URLs in [this commit](26d4a2af74cddb326e5966a5d42b5f4bba48e440) are changed from the GitHub project to a link to either the Google Play store (preferable if signing is worked out) or F-Droid.

**Comment by johanw666** [comment]
According to the documentation both values are too high: on https://developer.android.com/guide/topics/manifest/intent-filter-element.html I see:

android:priority
[...]
The value must be an integer, such as "100". Higher numbers have a higher priority. The default value is 0. The value must be greater than -1000 and less than 1000.

However, I see many sources suggestng that the highest value in practice is 2^32 - 1.

**Comment by pR0Ps** [comment]
@johanw666: please use the correct issue (#7) to discuss this.

**Comment by SecUpwN** [comment]
@BastienLQ, please do not just support the shitty Google PlayStore, but also publish via [Aptoide](http://www.aptoide.com/)! This is just my personal recommendation to you since I am also publishing my own App called [AIMSICD](https://secupwn.github.io/Android-IMSI-Catcher-Detector/) there - with huge success and great feedback from privacy-aware people that do not have GooglePlay or F-Droid installed.

**Comment by BoBeR182** [comment]
@SecUpwN While I agree that the Play Store is a terrible for your privacy, it is needed for typical uses to participate in encrypted conversations. When you want to trade your secret cookie recipe with grandma, copy pasting the Play Store link is better than Disable Unknown Sources >> Install F-Droid >> Install SMSSecure >> Manually Update. Compared to Open Play Store >> Install SMSSecure >> Autoupdates.
We should distribute as far and wide as possible, so Aptoide is an awesome extra.

**Comment by SecUpwN** [comment]
>We should distribute as far and wide as possible, so Aptoide is an awesome extra.

Thank you @BoBeR182, I'd very much enjoy getting it from there. Cheers!

**Comment by BastienLQ** [comment]
We will distribute SMSSecure via Aptoide, but after F-Droid and the Play Store: because F-Droid will be the official way to build SMSSecure (so we do not own the signing keys) and Play Store will allow to hit a huge audience.

**Comment by SecUpwN** [comment]
>We will distribute SMSSecure via Aptoide, but after F-Droid and the Play Store...

Why nit publish it there at the same time? I'd prefer getting it there since it is fully open source and thus I'd not have to uninstall SMSSecure when moving from F-Droid to Aptoide. What's the Issue?

**Comment by BastienLQ** [comment]
I mean that priority is given to the Play Store: if I have an issue when publishing the app there, I will first resolve that issue. But if everything is fine, the Aptoide build should be available almost in the same time.

**Comment by patcon** [comment]
> because F-Droid will be the official way to build SMSSecure (so we do not own the signing keys)

You should ask about "deterministic builds" in #fdroid or #guardianproject on irc

**Comment by CHEF-KOCH** [comment]
> XX ... please do not just support the shitty Google PlayStore, but also publish via Aptoide! This is just my personal recommendation to you since I am also publishing my own App called AIMSICD there - with huge success and great feedback from privacy-aware people no using GooglePlay or F-Droid.

Well, since Aptoide is a warez zone it's not a secret that it's more popular against other markets such as Google Play Store. In the top 50 there are 20 warez publisher guys widely known on cracking boards like XPDA/Xobilism/... and the Aptoide webmaster never answered my question why they not remove such "patched" apps or repos I would better to recommend to publish this here on GitHub and on F-Droid.

**Comment by pR0Ps** [comment]
@CHEF-KOCH: I have to agree.

Google Play, the Amazon app store, and F-Droid all have some credibility to them. The only time I've ever heard of Aptoide has been in relation to piracy and warez. Not something we really want to associate with. Plus, If we're on F-Droid, the APK is already available for download in a way that's not tied to any particular store.

Google play is the market for Android devices with GPS, Amazon is for amazon devices, and F-Droid is for the OSS crowd. We don't really gain much from being on Aptoide - there's no real specific market there.

**Comment by patcon** [comment]
:+1:

**Comment by johanw666** [comment]
I'd say we better publish it propper on Aptoide than someone else publishing a "patched" version that may contain a backdoor or adware.

**Comment by pR0Ps** [comment]
Someone publishing a malicious version of the apk is not something we can prevent.

On the website we will clearly list the official sources (and the source so they can build it themselves) and if people want to get it from somewhere else, they take their chances.

Besides, the "patched" versions are usually installed to get around paying for something. As we are a 100% free and open source app, there's nothing to gain from installing an unofficial apk.

**Comment by CHEF-KOCH** [comment]
Well it isn't about that that someone add malware to it or modify the apk itself and post it on the net (nobody can prevent it), it's more about that Aptoide becomes more and more a warez place (and the app itself is full of ads btw -> F-Droid no ads). So if you asking me we don't need to support that kind of market. As said the webmaster and supporters don't care about valid malware/patched arguments (maybe because they also use the patched stuff). There is a little icon and a small notice about different signatures, but that won't shown if you use scripts to download aptoide apk's directly on your pc and of course there is no warning or signature notification if you use the auto updater so that kind of "protection" only applies if you click on 'apk info'.

The benefit on F-Droid/Play/Github is that you can push or add a .asc or md5/sha1 ([whatever](https://f-droid.org/wiki/page/Deterministic,_Reproducible_Builds)) in the changelog to see if it's really the legit apk or not. F-Droid also found a good [solution](https://gitlab.com/fdroid/fdroidserver/commit/8568805866dadbdcc6c07449ca6b84b80d0ab03c).

> ... 100% free and open source app, there's nothing to gain from installing an unofficial apk.

Sure but Tor Browser bundle is also 100% and that package was faked several times with infected malware to get your data or redirect the whole traffic. Just saying. Freeware/open source or not there are always guys that tries to fake stuff or release there shit under different names on the market/net (and good example is also xposed installer with modded colors for lollipop or the famous youtube mods) - nobody really checked if it's clean or if it's not against there terms, stealing stuff, not giving any credit and release it under a modders name -> [WhatsAppalready banned such stuff](http://www.osmdroid.net/).

**Comment by johanw666** [comment]
Well, as a side note, the attacks on WhatsApp Plus have a little different background: the author asked money for some functionality, and deliberately deleted user content when pirated versions were used. WhatsApp Inc. got angry users with support questions that and understandibly didn't like it. The story is not well known for most people because it is described mostly on Spanish sites. This article on Slashdot gives some background: http://tech.slashdot.org/comments.pl?sid=6815551&cid=48895791

**Comment by pR0Ps** [comment]
Guys, this is getting off-topic.

We're going to release on F-Droid, Google Play, and the Amazon App Store.

**Comment by SecUpwN** [comment]
>I'd say we better publish it propper on Aptoide than someone else publishing a "patched" version that may contain a backdoor or adware.

>...it's more about that Aptoide becomes more and more a warez place... So if you asking me we don't need to support that kind of market.

Let me be very honest when I say that I don't like that you guys are discrediting @Aptoide to be a "warez store". I don't know which problems you had with them, @CHEF-KOCH, but support@aptoide.com always responded to me when explaining an Issue properly. Also, everyone is able to report warez content via the report button next to each App.

@BastienLQ already agreed on opening a store there and publishing the App with official signature and now all of a sudden you guys keep questioning his choice? As for me, I always had positive experiences with Aptoide since we also have [our own store](aimsicd.store.aptoide.com) there. One thing my team and I enjoy the most, is that we get weekly store statistics telling us how many users installed our App on which hardware and Android version. I'd rather use the official SMSSecure Aptoide store than finding your App through a different store with not matching signatures. You can also ask support to ensure that your store will be the only store where your APK is available (we're doing so already). So please rethink your choice against it.

**Comment by BastienLQ** [comment]
I agree with @pR0Ps and @CHEF-KOCH: Aptoide's reputation is bad. I'm open-minded and I believe having SMSSecure in other markets is a good thing. But it's not worth it if the cost is to not be trustworthy.
Because I didn't know Aptoide, I listened to you, as I listen to @pR0Ps and @CHEF-KOCH. And finally I agree with @pR0Ps: we won't publish SMSSecure to Aptoide. Users can always install APK from F-Droid without installing the F-Droid client, so we won't lose potential users.
In the same time, @pR0Ps suggests the Amazone Appstore, which is quite relevant in my opinion.

I'm locking this issue now. Feel free to continue it on the [#SMSSecure IRC channel](https://webchat.freenode.net/?channels=SMSSecure).
