### ISSUE TITLE
Publish signed APK in GitHub Releases

### ISSUE THREAD

**Issue by SecUpwN** [SMSSecure/SMSSecure#59]
Good evening @SMSSecure developers! Once again, let me state that I am very happy you guys keep making great progress, you've also just been covered on [Heise Security](http://heise.de/-2595471)! :+1: Please add yourself [here](https://www.eff.org/secure-messaging-scorecard)!

In conjunction with #4, I would love to see you publishing your signed APKs in [your GitHub Releases](https://github.com/SMSSecure/SMSSecure/releases) and add the MD5 sum for verification to it. I consider this especially important since you've [neglected Aptoide](https://github.com/SMSSecure/SMSSecure/issues/4#issuecomment-88238049) and likely not everyone is going to use F-Droid, GooglePlay or the Amazon store. With direct downloads, you'll cover everyone. You may use [our own GitHub Releases](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/releases) as a reference on how this could look like.

**Comment by pR0Ps** [comment]
Having an update mechanism is essential to any security-related app. This is so if a vulnerability is discovered, it can be patched and distributed to users quickly (and in some cases, automatically).

With that being said, if for some reason people really need to download the APK without installing anything else (F-Droid, Google Play, Amazon app store, etc), then they can download it from the F-Droid web site. As an example, [this is the page for the F-Droid app](https://f-droid.org/repository/browse/?fdid=org.fdroid.fdroid). Notice the direct APK and accompanying signature near the bottom of the page. To be clear: installing the APK from those links is **not recommended** due to the lack of updates, but is possible.

Having the exact same thing on GitHub doesn't add anything. They would be signed with the same key anyway.

Also, if you know the author of the article, I would urge you to get them to correct it. If the German -> English translation isn't wrong, it's saying that SMSSecure implements both encrypted SMS messages and the TextSecure push protocol. This is incorrect, SMSSecure **only** supports SMS/MMS for transport.

**Comment by SecUpwN** [comment]
Thanks @pR0Ps. I will contact the authors of the Heise article. Just for clarification: SMSSecure does **NOT** support the TextSecure protocol at all and **ONLY** the SMS encryption, nothing else, right?

**Comment by pR0Ps** [comment]
Correct, thanks for contacting them for us.

**Comment by fabsh** [comment]
Hi there! I am deeply sorry for the cofusion my article has caused. I have corrected it as soon as I was made aware. I guess I had misinterpreted your source. I was unfortunately not able to get my hands on an APK in the time available, otherwise I would have tested this myself. But luckily this issue is being adressed with this ticket. Your app was at the time not available from F-Droid.

**Comment by pR0Ps** [comment]
@fabsh Thanks for the writeup and for correcting it so quickly. If you'd like, you can now find SMSSecure in F-Droid at https://f-droid.org/repository/browse/?fdid=org.smssecure.smssecure .

**Comment by fabsh** [comment]
No thing, that's my job. I've also published another quick note telling people that it is now in F-Droid: http://www.heise.de/security/meldung/l-f-SMSSecure-jetzt-bei-F-Droid-erhaeltlich-2596566.html
