### ISSUE TITLE
Last version crashes after entering passphrase

### ISSUE THREAD

**Issue by jpfox** [SMSSecure/SMSSecure#61]
After installation of this version, I've got a progress bar to update database and apps has closed.

Now, every time I launch smssecure, I can enter my pass phrase and I got an error : "L'application SMSSecure s'est arrêtée"

State of compiled version : https://www.jpfox.fr/smssecure/git.txt

It's due to a today commit, yesterday, at commit 57c6eed4118061ebaffeb762033a1a5c944e14b3 it worked fine.

**Comment by jpfox** [comment]
After uninstall and reinstall app, it works... but I've lost my key and I have to reinitiate secure sessions with my friends.

**Comment by BastienLQ** [comment]
Can you provide a log, please?

**Comment by jpfox** [comment]
No, I've uninstalled app :-(

**Comment by matlink** [comment]
Got the same issue. How can I send you a log since the app doesn't start ?

**Comment by johanw666** [comment]
I was just about to enter an issue because I got the same. However, downgrading to a 0.4 version and then upgrading solved the issue. Since I use an XPosed module by LuckyPatcher to deactivate signature verification in the package manager I could downgrade while keeping the settings and database so I can confirm that a reinstall solves the issue. This is reporoducable on 2 devices.

Anyway, I think this is the significant part of the log:

04-03 11:16:08.984 E/AndroidRuntime(29641): FATAL EXCEPTION: pool-1-thread-1
04-03 11:16:08.984 E/AndroidRuntime(29641): java.lang.IllegalArgumentException: No inject registered for members/org.smssecure.smssecure.jobs.CreateSignedPreKeyJob. You must explicitly add it to the 'injects' option in one of your modules.
04-03 11:16:08.984 E/AndroidRuntime(29641): 	at dagger.ObjectGraph$DaggerObjectGraph.getInjectableTypeBinding(ObjectGraph.java:302)
04-03 11:16:08.984 E/AndroidRuntime(29641): 	at dagger.ObjectGraph$DaggerObjectGraph.inject(ObjectGraph.java:279)
04-03 11:16:08.984 E/AndroidRuntime(29641): 	at org.smssecure.smssecure.ApplicationContext.injectDependencies(ApplicationContext.java:67)
04-03 11:16:08.984 E/AndroidRuntime(29641): 	at org.whispersystems.jobqueue.persistence.PersistentStorage.injectDependencies(PersistentStorage.java:131)
04-03 11:16:08.984 E/AndroidRuntime(29641): 	at org.whispersystems.jobqueue.persistence.PersistentStorage.getJobs(PersistentStorage.java:98)
04-03 11:16:08.984 E/AndroidRuntime(29641): 	at org.whispersystems.jobqueue.persistence.PersistentStorage.getAllEncrypted(PersistentStorage.java:77)
04-03 11:16:08.984 E/AndroidRuntime(29641): 	at org.whispersystems.jobqueue.JobManager$LoadTask.run(JobManager.java:155)
04-03 11:16:08.984 E/AndroidRuntime(29641): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
04-03 11:16:08.984 E/AndroidRuntime(29641): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
04-03 11:16:08.984 E/AndroidRuntime(29641): 	at java.lang.Thread.run(Thread.java:838)
04-03 11:16:09.086 E/AppErrorDialog(15720): Failed to get ILowStorageHandle instance

**Comment by BastienLQ** [comment]
@matlink @jpfox You can get logs using `adb logcat` in debug mode. Anyway, as this issue only appears when migrating to SMSSecure 0.5.1, I don't think we'll fix it. That must be related to #3. @pR0Ps?

**Comment by johanw666** [comment]
Is this a one-time issue due to a database change between 0.4 and 0.5?

**Comment by BastienLQ** [comment]
As 0.5 works, even the passphrase feature, I think it is due to push-messages code removal.
This bug only affects people that built and installed SMSSecure <0.5.1, so I think it don't worth it to fix it.

**Comment by johanw666** [comment]
If it only affects this change, and re-installing it solves it I agree. Most 0.4 users compiled from source, the apk I put online was only downloaded 11 times and people got the link from here. I assume that those users are technically more savy than average.

**Comment by jpfox** [comment]
If you think it will not happen on each new version upgrade, you can close this issue.

**Comment by tuxayo** [comment]
What could be done to avoid such terrible situations where we have to wait maybe 24h for F-Droid to update with a non working app that prevent other apps to get SMS on older versions of android?
On the user side, a backup could be done to rollback the app if there is problem but only a minority of user would do this.
On the developer is there something to do?

**Comment by matlink** [comment]
@tuxayo, Compile the app yourself do the trick.

**Comment by tuxayo** [comment]
I can't install it without first uninstalling(loosing the DB) the build from F-Droid because of mismatching signatures.

**Comment by tuxayo** [comment]
With a fresh backup that would be an acceptable solution for savy users with the time to do this.

**Comment by matlink** [comment]
That's true.

**Comment by KaitoKito** [comment]
Should have read more the issue list.
Thanks pROPs, I'll wait until 0.5.3 is available to recover my messages (didn't uninstalled the app luckily).

**Comment by tuxayo** [comment]
0.5.3 published on F-Droid and problem solved!
Thanks @pR0Ps and @BastienLQ for your support through this first major bug!
