### ISSUE TITLE
Fetch translations from Transifex before releases

### ISSUE THREAD

**Issue by smarquespt** [SMSSecure/SMSSecure#93]
Please fetch translations from transifex before releases. I´ve made some changes to Portuguese translation (maybe other languages made them to) and I would like to see them in action in order to fix some mistakes I could have made.

**Comment by pR0Ps** [comment]
We usually do this, however since we had just updated the translations and were pushing out a critical bugfix, it slipped my mind. New translations will go into the next release.

In the meantime, you can check out [BUILDING.md](https://github.com/SMSSecure/SMSSecure/blob/master/BUILDING.md) for a guide on how to pull the latest translations and build the app locally so you're not dependent on the releases to test translations.
